// Libellés des succès (les objectifs et récompenses font foi côté serveur : g_achievement_defs)
export type AchGroup = 'Collection' | 'Photographe' | 'Combat' | 'Marché' | 'Social';
export const ACH: Record<string, { t: string; d: string; g: AchGroup; ic: string }> = {
  first_photo: { t: 'Premier déclic', d: 'Prends ta première photo', g: 'Photographe', ic: '◉' },
  shots_100: { t: 'Œil affûté', d: 'Prends 100 photos', g: 'Photographe', ic: '◉' },
  shots_500: { t: 'Reporter animalier', d: 'Prends 500 photos', g: 'Photographe', ic: '◉' },
  night_20: { t: 'Oiseau de nuit', d: 'Prends 20 photos la nuit', g: 'Photographe', ic: '☾' },
  perfect_1: { t: 'Cliché parfait', d: 'Obtiens une photo « parfaite »', g: 'Photographe', ic: '✦' },
  perfect_10: { t: "Maître de l'objectif", d: 'Possède 10 photos « parfaites »', g: 'Photographe', ic: '✦' },
  biomes_6: { t: 'Globe-trotteur', d: 'Photographie dans les 6 milieux', g: 'Photographe', ic: '⌘' },
  species_10: { t: 'Curieux de nature', d: '10 espèces de France', g: 'Collection', ic: '❦' },
  species_50: { t: 'Naturaliste', d: '50 espèces de France', g: 'Collection', ic: '❦' },
  species_150: { t: 'Encyclopédiste', d: '150 espèces de France', g: 'Collection', ic: '❦' },
  species_400: { t: 'Buffon moderne', d: '400 espèces de France', g: 'Collection', ic: '❦' },
  birds_25: { t: 'Ornithologue', d: "25 espèces d'oiseaux", g: 'Collection', ic: '⌃' },
  mammals_10: { t: 'Mammalogiste', d: '10 espèces de mammifères', g: 'Collection', ic: '⌃' },
  insects_25: { t: 'Entomologiste', d: "25 espèces d'insectes", g: 'Collection', ic: '⌃' },
  epic_1: { t: 'Belle rencontre', d: 'Trouve une espèce épique', g: 'Collection', ic: '◆' },
  legend_1: { t: 'Légende vivante', d: 'Trouve une espèce légendaire', g: 'Collection', ic: '★' },
  legend_5: { t: 'Chasseur de légendes', d: '5 espèces légendaires', g: 'Collection', ic: '★' },
  world_3: { t: 'Collectionneur du monde', d: '3 espèces étrangères', g: 'Collection', ic: '⊕' },
  lvl_3: { t: 'Cadre bronze', d: 'Une carte au niveau 3', g: 'Collection', ic: '▲' },
  lvl_5: { t: 'Cadre argent', d: 'Une carte au niveau 5', g: 'Collection', ic: '▲' },
  lvl_7: { t: 'Cadre parfait', d: 'Une carte au niveau 7', g: 'Collection', ic: '▲' },
  fusions_10: { t: 'Alchimiste', d: 'Réalise 10 fusions', g: 'Collection', ic: '⇪' },
  fusions_50: { t: 'Grand alchimiste', d: 'Réalise 50 fusions', g: 'Collection', ic: '⇪' },
  wins_10: { t: 'Dresseur', d: 'Gagne 10 combats sauvages', g: 'Combat', ic: '⚔' },
  wins_50: { t: 'Champion des bois', d: 'Gagne 50 combats sauvages', g: 'Combat', ic: '⚔' },
  duel_5: { t: 'Duelliste', d: 'Gagne 5 duels contre des joueurs', g: 'Combat', ic: '⚔' },
  sales_1: { t: 'Première vente', d: 'Vends une carte aux enchères', g: 'Marché', ic: '¤' },
  sales_10: { t: 'Négociant', d: 'Vends 10 cartes aux enchères', g: 'Marché', ic: '¤' },
  friend_1: { t: 'Compagnon de safari', d: 'Ajoute un ami', g: 'Social', ic: '♥' },
  friend_5: { t: 'Bande de naturalistes', d: 'Aie 5 amis', g: 'Social', ic: '♥' },
  guild_1: { t: 'Esprit de meute', d: 'Rejoins ou fonde une guilde', g: 'Social', ic: '⚑' },
};
export const GROUPS: AchGroup[] = ['Collection', 'Photographe', 'Combat', 'Marché', 'Social'];
