// Tests de la base Bestiaire sur un PostgreSQL local (émulation Supabase).
// Usage : PGHOST=/tmp/pgtest PGPORT=54329 PGUSER=postgres PGDATABASE=bestiaire node supabase/tests/db.test.mjs
import pg from 'pg';
const db = new pg.Pool();
let pass = 0, fail = 0;
const ok = (c, m) => { if (c) { pass++; console.log('  ✓', m) } else { fail++; console.log('  ✗', m) } };
async function as(uid, sql, params = []) {
  const c = await db.connect();
  try {
    await c.query('begin');
    await c.query(`select set_config('request.jwt.claim.sub', $1, true)`, [uid || '']);
    await c.query(uid ? 'set local role authenticated' : 'set local role anon');
    const r = await c.query(sql, params); await c.query('commit'); return r;
  } catch (e) { await c.query('rollback'); throw e } finally { c.release() }
}
const fails = async (p) => { try { await p; return null } catch (e) { return e.message } };
const admin = (sql, p) => db.query(sql, p);

await admin('truncate public.notifications, public.push_subscriptions, public.reports, public.blocks cascade');
await admin('truncate public.guild_messages, public.guild_members, public.guilds, public.friendships cascade');
await admin('truncate public.cards, public.auctions, public.sales, public.bot_offers, public.defenses, public.duels, public.profiles cascade; delete from auth.users;');
const A = (await admin(`insert into auth.users(email) values ('a@test.fr') returning id`)).rows[0].id;
const B = (await admin(`insert into auth.users(email) values ('b@test.fr') returning id`)).rows[0].id;
const C = (await admin(`insert into auth.users(email) values ('c@test.fr') returning id`)).rows[0].id;

console.log('Profils et état');
let st = (await as(A, 'select get_state() s')).rows[0].s;
ok(st.plumes === 50 && st.films === 3, 'nouveau joueur : 50 plumes, 3 pellicules');
ok(['F','P','H','M','V','L'].includes(st.daily_biome), 'biome du jour fourni par le serveur');
ok(Array.isArray(st.quests) && st.quests.length === 3, '3 défis du jour');
ok(st.premium === false && st.film_cap === 6, 'non premium : réserve de 6');

console.log('Sécurité (RLS)');
ok(await fails(as(A, `update profiles set plumes = 99999 where id = $1`, [A])) !== null, 'impossible de modifier ses plumes directement');
ok(await fails(as(A, `update profiles set premium_until = now() + interval '1 year' where id = $1`, [A])) !== null, 'impossible de s’offrir le premium');
ok(await fails(as(A, `insert into cards(owner, species_id, q) values ($1, 'lynx-lynx', 99)`, [A])) !== null, 'impossible de se créer une carte');
const upd = await as(A, `update profiles set pseudo = 'Victor' where id = $1 returning pseudo`, [A]);
ok(upd.rows[0]?.pseudo === 'Victor', 'pseudo modifiable');
ok((await as(B, `select * from profiles where id = $1`, [A])).rowCount === 0, 'B ne voit pas le profil de A');
ok(await fails(as(null, 'select get_state()')) !== null, 'visiteur non connecté refusé');

console.log('Safari');
const shot = (await as(A, `select safari_shoot('F') r`)).rows[0].r;
ok(shot.length === 5, '5 photos par pellicule');
const sp = (await admin(`select id, biomes, pays from species where id = any($1)`, [shot.map(x => x.species_id)])).rows;
ok(sp.every(s => s.biomes.includes('F') && !s.pays), 'toutes les espèces vivent en forêt et sont françaises');
ok(shot.every(x => x.q >= 0 && x.q <= 99 && x.lvl === 1), 'qualité 0–99, niveau 1');
st = (await as(A, 'select get_state() s')).rows[0].s;
ok(st.films === 2 && st.next_film_at, 'une pellicule consommée, recharge programmée');
await as(A, `select safari_shoot('P')`); await as(A, `select safari_shoot('H')`);
ok(await fails(as(A, `select safari_shoot('M')`)) !== null, 'refus quand il n’y a plus de pellicule');
ok(await fails(as(A, `select safari_shoot('Z')`)) !== null, 'biome inconnu refusé');
const cardsA = (await as(A, 'select count(*)::int n from cards')).rows[0].n;
ok(cardsA === 15, '15 cartes visibles pour A');
ok((await as(B, 'select count(*)::int n from cards')).rows[0].n === 0, 'B ne voit pas les cartes de A');

console.log('Recharge');
await admin(`update profiles set films = 0, films_at = now() - interval '2 hours 5 minutes' where id = $1`, [A]);
st = (await as(A, 'select get_state() s')).rows[0].s;
ok(st.films === 2, '+2 pellicules après 2 h');
await admin(`update profiles set films = 0, films_at = now() - interval '30 hours' where id = $1`, [A]);
ok((await as(A, 'select get_state() s')).rows[0].s.films === 6, 'plafond de 6');

console.log('Premium');
await admin(`update profiles set premium_until = now() + interval '30 days', films = 0, films_at = now() - interval '81 minutes' where id = $1`, [B]);
st = (await as(B, 'select get_state() s')).rows[0].s;
ok(st.premium && st.film_cap === 9 && st.film_minutes === 40, 'premium : réserve 9, recharge 40 min');
ok(st.films === 2, 'premium : +2 pellicules après 81 min');
await admin(`update profiles set films = 0, films_at = now() - interval '30 hours' where id = $1`, [B]);
ok((await as(B, 'select get_state() s')).rows[0].s.films === 9, 'premium : plafond de 9');
await admin(`update profiles set premium_until = now() - interval '1 day' where id = $1`, [B]);
ok((await as(B, 'select get_state() s')).rows[0].s.premium === false, 'abonnement expiré : plus premium');

console.log('Tirage : distribution des raretés (2 000 photos)');
await admin(`update profiles set films = 400 where id = $1`, [C]);
const daily = (await as(C, 'select get_state() s')).rows[0].s.daily_biome; const tb = daily === 'P' ? 'F' : 'P';
const tiers = [0,0,0,0,0]; let night = 0, total = 0;
for (let i = 0; i < 400; i++) { const r = (await as(C, `select safari_shoot($1) r`, [tb])).rows[0].r; for (const x of r) { total++; } }
const dist = (await admin(`select s.tier, count(*)::int n from cards c join species s on s.id = c.species_id where c.owner = $1 group by 1 order by 1`, [C])).rows;
dist.forEach(r => tiers[r.tier] = r.n);
const pct = tiers.map(n => Math.round(1000 * n / total) / 10);
console.log(`    répartition commun→légendaire en ${tb} (%) :`, pct.join(' / '));
ok((await admin(`select count(*)::int n from cards c join species s on s.id = c.species_id where c.owner = $1 and s.sprite is null`, [C])).rows[0].n === 0, 'jamais d’espèce sans photo');
ok((await admin(`select g_cote(0,1,80,false) a, g_cote(2,3,95,true) b`)).rows[0].a === 7, 'cote arrondie comme dans l’application (6,5 → 7)');
ok(pct[0] > 52 && pct[0] < 68 && pct[1] > 19 && pct[1] < 31 && pct[2] > 6 && pct[2] < 14 && pct[3] < 7, 'répartition proche de 60/25/10/4/1');

console.log('Fusion');
await admin(`delete from cards where owner = $1`, [A]);
await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'lynx-lynx',30,1),($1,'lynx-lynx',90,1),($1,'lynx-lynx',50,2)`, [A]);
const f = (await as(A, `select fuse('lynx-lynx', 1) r`)).rows[0].r;
ok(f.lvl === 2 && f.q === 90, 'deux niveau 1 → niveau 2, meilleure photo gardée');
ok(await fails(as(A, `select fuse('lynx-lynx', 1)`)) !== null, 'refus sans deux exemplaires du même niveau');
const f2 = (await as(A, `select fuse('lynx-lynx', 2) r`)).rows[0].r;
ok(f2.lvl === 3 && (await as(A, `select count(*)::int n from cards`)).rows[0].n === 1, 'niveau 3, plus qu’une carte');
let ups = 0, perf = 0;
for (let i = 0; i < 200; i++) { await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'parus-major',85,1),($1,'parus-major',86,1)`, [A]); const r = (await as(A, `select fuse('parus-major', 1) r`)).rows[0].r; if (r.up) ups++; if (r.q >= 95) perf++; }
ok(perf === 0, 'deux « superbe » ne donnent jamais « parfaite »');
for (let i = 0; i < 200; i++) { await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'pica-pica',10,1),($1,'pica-pica',20,1)`, [A]); const r = (await as(A, `select fuse('pica-pica', 1) r`)).rows[0].r; if (r.up) ups++; }
ok(ups > 25 && ups < 85, `~25 % d’amélioration entre deux floues (${ups}/200)`);

console.log('Marché : enchères');
await admin(`update profiles set plumes = 1000 where id in ($1,$2,$3)`, [A, B, C]);
const card = (await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'vulpes-vulpes',70,2) returning id`, [A])).rows[0].id;
ok(await fails(as(B, `select list_auction($1, 10, null, 60)`, [card])) !== null, 'B ne peut pas vendre la carte de A');
const aid = (await as(A, `select list_auction($1, 20, 200, 60) r`, [card])).rows[0].r;
ok((await as(A, `select status from cards where id = $1`, [card])).rows[0].status === 'auction', 'carte bloquée pendant la vente');
const tmp = (await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'vulpes-vulpes',10,2) returning id`, [A])).rows[0].id;
ok(await fails(as(A, `select fuse('vulpes-vulpes', 2)`)) !== null, 'carte en vente exclue des fusions');
await admin(`delete from cards where id = $1`, [tmp]);
ok(await fails(as(A, `select place_bid($1, 30)`, [aid])) !== null, 'le vendeur ne peut pas enchérir');
ok(await fails(as(B, `select place_bid($1, 10)`, [aid])) !== null, 'mise inférieure au départ refusée');
await as(B, `select place_bid($1, 20)`, [aid]);
ok((await admin(`select plumes from profiles where id = $1`, [B])).rows[0].plumes === 980, 'B : 20 plumes bloquées');
ok(await fails(as(C, `select place_bid($1, 20)`, [aid])) !== null, 'surenchère < +5 % refusée');
await as(C, `select place_bid($1, 30)`, [aid]);
ok((await admin(`select plumes from profiles where id = $1`, [B])).rows[0].plumes === 1000, 'B remboursé quand C surenchérit');
await as(C, `select place_bid($1, 40)`, [aid]);
ok((await admin(`select plumes from profiles where id = $1`, [C])).rows[0].plumes === 960, 'C relance : ne paie que la différence');
await admin(`update auctions set ends_at = now() + interval '30 seconds' where id = $1`, [aid]);
await as(B, `select place_bid($1, 50)`, [aid]);
ok((await admin(`select ends_at > now() + interval '100 seconds' ok from auctions where id = $1`, [aid])).rows[0].ok, 'offre de dernière minute : +2 min');
await admin(`update auctions set ends_at = now() - interval '1 second' where id = $1`, [aid]);
await as(A, `select get_state()`);
const sold = (await admin(`select status, best_bid from auctions where id = $1`, [aid])).rows[0];
ok(sold.status === 'sold' && sold.best_bid === 50, 'enchère clôturée et vendue 50');
ok((await admin(`select owner from cards where id = $1`, [card])).rows[0].owner === B, 'carte transférée au gagnant');
ok((await admin(`select plumes from profiles where id = $1`, [A])).rows[0].plumes === 1050, 'vendeur payé');
ok((await admin(`select plumes from profiles where id = $1`, [C])).rows[0].plumes === 1000, 'perdant remboursé');
ok((await as(A, `select count(*)::int n from sales where species_id = 'vulpes-vulpes'`)).rows[0].n === 1, 'vente dans l’historique');
const card2 = (await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'lynx-lynx',99,1) returning id`, [A])).rows[0].id;
const aid2 = (await as(A, `select list_auction($1, 100, 300, 10) r`, [card2])).rows[0].r;
const bn = (await as(C, `select place_bid($1, 300) r`, [aid2])).rows[0].r;
ok(bn.bought && (await admin(`select owner from cards where id = $1`, [card2])).rows[0].owner === C, 'achat immédiat : carte transférée tout de suite');
ok(await fails(as(A, `select list_auction($1, 10, null, 7)`, [card])) !== null, 'durée hors liste refusée');
const cardU = (await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'turdus-merula',50,1) returning id`, [A])).rows[0].id;
const aidU = (await as(A, `select list_auction($1, 9999, null, 10) r`, [cardU])).rows[0].r;
await admin(`update auctions set ends_at = now() - interval '1 second' where id = $1`, [aidU]);
await as(A, `select settle_auctions()`);
ok((await admin(`select status from cards where id = $1`, [cardU])).rows[0].status === 'owned', 'sans acheteur à prix excessif : l’animal revient');
ok(await fails(as(A, `update auctions set best_bid = 1 where id = $1`, [aid])) !== null, 'impossible de modifier une enchère directement');

console.log('Marché : collectionneurs et vente rapide');
const offers = (await as(A, `select * from get_bot_offers()`)).rows;
ok(offers.length === 8, '8 offres de collectionneurs');
ok(offers.filter(o => o.species_id.startsWith('x-')).length >= 2, 'au moins 2 espèces étrangères');
const cheap = offers.sort((a, b) => a.price - b.price)[0];
const before = (await admin(`select plumes from profiles where id = $1`, [A])).rows[0].plumes;
await as(A, `select buy_bot_offer($1)`, [cheap.id]);
ok((await admin(`select plumes from profiles where id = $1`, [A])).rows[0].plumes === before - cheap.price, 'achat débité');
ok(await fails(as(B, `select buy_bot_offer($1)`, [cheap.id])) !== null, 'offre déjà vendue indisponible');
const qs = (await as(A, `select quick_sell($1) r`, [cardU])).rows[0].r;
ok(qs === 3, 'vente rapide à 60 % de la cote (merle nette niv. 1 = 3 plumes)');

console.log('Défis');
await admin(`update profiles set quests = jsonb_set(quests, '{0,prog}', to_jsonb((quests->0->>'goal')::int)) where id = $1`, [A]);
const rw = (await as(A, `select claim_quest(0) r`)).rows[0].r;
ok(rw && (rw.plumes || rw.films), 'récompense de défi récupérée');
ok(await fails(as(A, `select claim_quest(0)`)) !== null, 'pas de double récupération');
await admin(`update profiles set quests = jsonb_set(quests, '{1,prog}', '0') where id = $1`, [A]);
ok(await fails(as(A, `select claim_quest(1)`)) !== null, 'défi non terminé refusé');

console.log('Combats');
const w = (await as(A, `select battle_reward(true, array['lynx-lynx','parus-major'], array[3,1]) r`)).rows[0].r;
ok(w.gain === 6*5*3 + 6*1*1, `gain = 6 × (rareté+1) × niveau (${w.gain})`);
const big = (await as(A, `select battle_reward(true, array['lynx-lynx','lynx-lynx','lynx-lynx'], array[7,7,7]) r`)).rows[0].r;
ok(big.gain === 400, 'gain plafonné à 400');
await admin(`update profiles set rewards_count = 30 where id = $1`, [A]);
ok((await as(A, `select battle_reward(true, array['lynx-lynx'], array[1]) r`)).rows[0].r.gain === 0, '30 récompenses par jour maximum');
const cB = (await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'ursus-arctos',60,2) returning id`, [B])).rows[0].id;
ok(await fails(as(A, `select save_defense(array[$1::bigint])`, [cB])) !== null, 'impossible d’enregistrer la carte d’un autre en défense');
await as(B, `select save_defense(array[$1::bigint])`, [cB]);
ok((await as(A, `select count(*)::int n from defenses`)).rows[0].n === 1, 'défense de B visible par tous');
const d = (await as(A, `select record_duel($1, true) r`, [B])).rows[0].r;
ok(d.delta > 0 && d.gain > 15, `victoire en duel : +${d.delta} points, +${d.gain} plumes`);
ok(await fails(as(B, `select record_duel($1, true)`, [B])) !== null, 'pas de duel contre soi-même');
await admin(`update profiles set duels_count = 20 where id = $1`, [A]);
ok(await fails(as(A, `select record_duel($1, true)`, [B])) !== null, '20 duels par jour maximum');


console.log('Compteurs et succès');
await admin(`update profiles set plumes = 1000, films = 6, films_at = now(), shots = 0, achievements = '{}' where id = $1`, [C]);
const shots0 = (await admin(`select shots, week_shots from profiles where id = $1`, [C])).rows[0];
await as(C, `select safari_shoot('F')`);
const shots1 = (await admin(`select shots, week_shots from profiles where id = $1`, [C])).rows[0];
ok(shots1.shots === shots0.shots + 5 && shots1.week_shots >= 5, 'chaque photo est comptée (succès + objectif de guilde)');
let ach = (await as(C, `select get_achievements() a`)).rows[0].a;
ok(ach.length >= 30 && ach.every(x => x.goal > 0), `${ach.length} succès définis`);
const fp = ach.find(x => x.code === 'first_photo');
ok(fp.prog === 1 && !fp.claimed, 'succès « première photo » atteint');
const pl0 = (await admin(`select plumes from profiles where id = $1`, [C])).rows[0].plumes;
await as(C, `select claim_achievement('first_photo')`);
ok((await admin(`select plumes from profiles where id = $1`, [C])).rows[0].plumes === pl0 + 20, 'récompense du succès créditée');
ok(await fails(as(C, `select claim_achievement('first_photo')`)) !== null, 'pas de double récompense');
ok(await fails(as(C, `select claim_achievement('legend_5')`)) !== null, 'succès non atteint refusé');
ok(await fails(as(C, `select claim_achievement('nimporte')`)) !== null, 'succès inconnu refusé');
await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'parus-major',50,1),($1,'parus-major',60,1)`, [C]);
const fz0 = (await admin(`select fusions from profiles where id = $1`, [C])).rows[0].fusions;
await as(C, `select fuse('parus-major', 1)`);
ok((await admin(`select fusions from profiles where id = $1`, [C])).rows[0].fusions === fz0 + 1, 'fusion comptée');
ok(await fails(as(C, `update profiles set achievements = '{legend_5}' where id = auth.uid()`)) !== null, 'impossible de s’attribuer un succès directement');

console.log('Amis');
const fa = (await as(A, `select get_friends() f`)).rows[0].f, fb = (await as(B, `select get_friends() f`)).rows[0].f;
ok(/^[A-Z0-9]{6}$/.test(fa.code) && fa.code !== fb.code, `codes amis uniques (${fa.code}, ${fb.code})`);
ok(await fails(as(A, `select friend_request($1)`, [fa.code])) !== null, 'impossible de s’ajouter soi-même');
ok(await fails(as(A, `select friend_request('ZZZZZZ')`)) !== null, 'code inconnu refusé');
ok((await as(A, `select friend_request($1) r`, [fb.code.toLowerCase()])).rows[0].r === 'pending', 'demande envoyée (code insensible à la casse)');
let lb = (await as(B, `select get_friends() f`)).rows[0].f.list;
ok(lb.length === 1 && lb[0].incoming && lb[0].status === 'pending', 'B voit la demande entrante');
ok(await fails(as(A, `select friend_respond($1, true)`, [B])) !== null, 'A ne peut pas accepter sa propre demande');
ok(await fails(as(A, `select friend_profile($1)`, [B])) !== null, 'profil invisible avant acceptation');
await as(B, `select friend_respond($1, true)`, [A]);
const la = (await as(A, `select get_friends() f`)).rows[0].f.list;
ok(la.length === 1 && la[0].status === 'accepted' && la[0].defense === true, 'amis ; la défense de B est signalée');
const prof = (await as(A, `select friend_profile($1) p`, [B])).rows[0].p;
ok(prof.top.length >= 1 && prof.metrics.species >= 1, 'profil de l’ami : ses cartes et statistiques');
ok((await as(C, `select count(*)::int n from friendships`)).rows[0].n === 0, 'C ne voit pas les amitiés des autres');
ok(await fails(as(C, `select friend_profile($1)`, [B])) !== null, 'C ne voit pas le profil de B');
await as(C, `select friend_request($1)`, [fa.code]); await as(A, `select friend_request($1)`, [(await as(C, `select get_friends() f`)).rows[0].f.code]);
ok((await as(A, `select get_friends() f`)).rows[0].f.list.filter(x => x.status === 'accepted').length === 2, 'demandes croisées : acceptation automatique');
await as(A, `select friend_remove($1)`, [C]);
ok((await as(A, `select get_friends() f`)).rows[0].f.list.length === 1, 'ami retiré');

console.log('Guildes');
await admin(`update profiles set plumes = 50 where id = $1`, [A]);
ok(await fails(as(A, `select guild_create('Les Hiboux','HIB','Nuit','parus-major')`)) !== null, 'fonder une guilde coûte 100 plumes');
await admin(`update profiles set plumes = 500 where id in ($1,$2,$3)`, [A, B, C]);
ok(await fails(as(A, `select guild_create('Les Hiboux','HIB','Nuit','ursus-arctos')`)) !== null, 'emblème : un animal de sa collection');
ok(await fails(as(A, `select guild_create('Les Hiboux','hib!','Nuit',null)`)) !== null, 'sigle invalide refusé');
const gid = (await as(A, `select guild_create('Les Hiboux','hib','Photographes de nuit',null) g`)).rows[0].g;
ok(gid > 0 && (await admin(`select plumes from profiles where id = $1`, [A])).rows[0].plumes === 400, 'guilde fondée (−100 plumes), sigle en majuscules');
ok(await fails(as(B, `select guild_create('les hiboux','HB2','',null)`)) !== null, 'nom déjà pris (même casse différente)');
ok(await fails(as(A, `select guild_join($1)`, [gid])) !== null, 'déjà membre');
ok((await as(B, `select guild_list('hib') l`)).rows[0].l.length === 1, 'recherche de guilde');
await as(B, `select guild_join($1)`, [gid]);
let g = (await as(B, `select guild_get() g`)).rows[0].g;
ok(g.members.length === 2 && g.role === 'membre' && g.week.goal === 80, 'B rejoint ; objectif de la semaine 40 photos × 2 membres');
await as(B, `select guild_post('Salut la guilde !')`);
ok(await fails(as(B, `select guild_post('encore')`)) !== null, 'anti-spam : 3 secondes entre deux messages');
ok(await fails(as(B, `select guild_post($1)`, ['x'.repeat(201)])) !== null, 'message limité à 200 caractères');
ok((await as(A, `select count(*)::int n from guild_messages where body like 'Salut%'`)).rows[0].n === 1, 'A lit les messages de sa guilde');
ok((await as(C, `select count(*)::int n from guild_messages`)).rows[0].n === 0, 'C (hors guilde) ne lit pas les messages');
ok(await fails(as(B, `select guild_manage($1,'exclure')`, [A])) !== null, 'un membre ne peut pas exclure le chef');
ok(await fails(as(B, `insert into guild_members(user_id, guild_id, role) values ($1, $2, 'chef')`, [C, gid])) !== null, 'pas d’écriture directe dans les guildes');
ok(await fails(as(B, `select guild_claim_week()`)) !== null, 'récompense refusée tant que l’objectif n’est pas atteint');
await admin(`update profiles set week_shots = 40, week_of = date_trunc('week', now())::date where id in ($1,$2)`, [A, B]);
const pb = (await admin(`select plumes, films from profiles where id = $1`, [A])).rows[0];
await as(A, `select guild_claim_week()`);
const pb2 = (await admin(`select plumes, films from profiles where id = $1`, [A])).rows[0];
ok(pb2.plumes === pb.plumes + 60 && pb2.films === pb.films + 1, 'objectif atteint : +60 plumes, +1 pellicule');
ok(await fails(as(A, `select guild_claim_week()`)) !== null, 'une seule récompense par semaine');
ok(await fails(as(B, `select guild_claim_week()`)) !== null, 'un nouveau membre attend la semaine suivante (pas de « saute-guilde »)');
ok((await as(B, `select friend_profile($1) p`, [A])).rows[0].p.pseudo !== undefined, 'profil visible entre membres de la guilde');
await as(A, `select guild_manage($1,'promouvoir')`, [B]);
await as(A, `select guild_leave()`);
g = (await as(B, `select guild_get() g`)).rows[0].g;
ok(g && g.role === 'chef' && g.members.length === 1, 'le chef part : l’officier devient chef');
ach = (await as(B, `select get_achievements() a`)).rows[0].a;
ok(ach.find(x => x.code === 'guild_1').prog === 1 && ach.find(x => x.code === 'friend_1').prog === 1, 'succès « guilde » et « ami » atteints');
await as(B, `select guild_leave()`);
ok((await admin(`select count(*)::int n from guilds where id = $1`, [gid])).rows[0].n === 0, 'guilde vide supprimée');

console.log('Notifications');
const notifs = async (u) => (await as(u, 'select get_notifications() n')).rows[0].n;
await admin(`update profiles set notif = '{"pellicules":true,"encheres":true,"amis":true,"guilde":true,"duels":true}', plumes = 2000 where id in ($1,$2,$3)`, [A, B, C]);
await as(A, 'select mark_notifications_read()'); await as(B, 'select mark_notifications_read()'); await as(C, 'select mark_notifications_read()');
const cardN = (await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'vulpes-vulpes',70,1) returning id`, [A])).rows[0].id;
const aucN = (await as(A, `select list_auction($1, 10, null, 60) r`, [cardN])).rows[0].r;
await as(B, `select place_bid($1, 10)`, [aucN]); await as(C, `select place_bid($1, 20)`, [aucN]);
let nb = await notifs(B);
ok(nb.unread === 1 && nb.list[0].title === 'Enchère dépassée' && nb.list[0].tab === 'market', 'B prévenu : enchère dépassée');
await admin(`update auctions set ends_at = now() - interval '1 second' where id = $1`, [aucN]); await as(A, 'select settle_auctions()');
ok((await notifs(A)).list.some(n => n.title === 'Vendu !') && (await notifs(C)).list.some(n => n.title === 'Enchère remportée'), 'vendeur et acheteur prévenus à la clôture');
ok((await as(B, `select count(*)::int n from notifications`)).rows[0].n === (await notifs(B)).list.length, 'chacun ne lit que ses notifications');
await as(B, 'select mark_notifications_read()'); ok((await notifs(B)).unread === 0, 'notifications marquées comme lues');
await as(B, `select set_notif_prefs('{"encheres": false}'::jsonb)`);
const cardN2 = (await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'vulpes-vulpes',70,1) returning id`, [A])).rows[0].id;
const aucN2 = (await as(A, `select list_auction($1, 10, null, 60) r`, [cardN2])).rows[0].r;
await as(B, `select place_bid($1, 10)`, [aucN2]); await as(C, `select place_bid($1, 20)`, [aucN2]);
ok((await notifs(B)).unread === 0, 'type de notification désactivé : plus rien');
await as(B, `select set_notif_prefs('{}'::jsonb)`);
const codeB = (await as(B, 'select get_friends() f')).rows[0].f.code;
await as(C, 'select mark_notifications_read()'); await as(C, `select friend_request($1)`, [codeB]);
ok((await notifs(B)).list[0].title === 'Demande d’ami'.replace('’', "'"), 'demande d’ami notifiée');
await as(B, `select friend_respond($1, true)`, [C]);
ok((await notifs(C)).list[0].title === 'Nouvel ami', 'acceptation notifiée');
await admin(`update profiles set duels_count = 0 where id = $1`, [C]);
await as(C, `select record_duel($1, true)`, [B]);
ok((await notifs(B)).list[0].title === 'Ta défense a été attaquée', 'défense attaquée notifiée');
const gidN = (await as(B, `select guild_create('Les Renards','REN','',null) g`)).rows[0].g;
await as(C, `select guild_join($1)`, [gidN]); await as(B, 'select mark_notifications_read()');
await as(C, `select guild_post('Bonjour !')`); await admin(`update guild_messages set at = at - interval '5 seconds'`);
await as(C, `select guild_post('Encore moi')`);
ok((await notifs(B)).list.filter(n => n.title === 'Les Renards').length === 1, 'messages de guilde : une seule notification non lue à la fois');
ok(await fails(as(B, `select push_subscribe('http://pas-https', 'x', 'y')`)) !== null, 'abonnement push : adresse https obligatoire');
await as(B, `select push_subscribe('https://push.example/abc', 'cle', 'auth')`);
ok((await notifs(B)).push === 1 && await fails(as(B, `select * from push_subscriptions`)) !== null, 'abonnement push enregistré, illisible directement');
await admin(`update profiles set films = 1, films_at = now() - interval '10 hours', films_notified_at = null, premium_until = null where id = $1`, [B]);
ok((await admin('select notify_full_films() n')).rows[0].n >= 1 && (await notifs(B)).list[0].title === 'Pellicules rechargées', 'pellicules rechargées notifiées (joueurs abonnés au push)');
ok((await admin('select notify_full_films() n')).rows[0].n === 0, 'une seule fois par recharge');

console.log('Modération');
for (const bad of ['Connard', 'sale Jüif', 'p.u.t.e', 'Enculé', 'N1gger']) {
  const r = await fails(as(C, `update profiles set pseudo = $1 where id = auth.uid()`, [bad]));
  if (bad === 'p.u.t.e') continue; // la ponctuation contourne le filtre : les signalements prennent le relais
  ok(r !== null, `pseudo « ${bad} » refusé`);
}
ok(await fails(as(C, `update profiles set pseudo = 'Admin Bestiaire' where id = auth.uid()`)) !== null, 'pseudo réservé refusé');
for (const good of ['Conifère', 'Victor09', 'Pédalo', 'Violette']) ok(await fails(as(C, `update profiles set pseudo = $1 where id = auth.uid()`, [good])) === null, `pseudo « ${good} » accepté`);
ok(await fails(as(C, `select guild_post('t''es un connard')`)) !== null, 'insulte refusée dans la discussion');
ok(await fails(as(A, `select guild_create('Les Nazis','NZ','',null)`)) !== null, 'nom de guilde haineux refusé');
await admin(`update guild_messages set at = at - interval '5 seconds'`);
await as(C, `select guild_post('Message limite')`);
const mid = (await admin(`select id from guild_messages where body = 'Message limite'`)).rows[0].id;
const D2 = (await admin(`insert into auth.users(email) values ('e@test.fr') returning id`)).rows[0].id;
const D3 = (await admin(`insert into auth.users(email) values ('f@test.fr') returning id`)).rows[0].id;
await as(D2, 'select get_state()'); await as(D3, 'select get_state()');
await admin(`insert into guild_members(user_id, guild_id) values ($1,$3),($2,$3)`, [D2, D3, gidN]);
ok(await fails(as(A, `select report('message', $1, 'insulte')`, [String(mid)])) !== null, 'impossible de signaler un message d’une autre guilde');
await as(B, `select report('message', $1, 'insulte')`, [String(mid)]);
await as(B, `select report('message', $1, 'insulte')`, [String(mid)]);
await as(D2, `select report('message', $1, 'harcelement')`, [String(mid)]);
ok((await admin(`select hidden from guild_messages where id = $1`, [mid])).rows[0].hidden === false, 'deux signaleurs : message encore visible (doublon ignoré)');
ok((await as(D3, `select report('message', $1, 'haine') r`, [String(mid)])).rows[0].r === 'masqué', 'trois joueurs différents : message masqué automatiquement');
ok(!(await as(B, 'select guild_get() g')).rows[0].g.messages.some(m => m.body === 'Message limite'), 'message masqué invisible pour la guilde');
await as(B, `select block_user($1, true)`, [C]);
ok(!(await as(B, 'select guild_get() g')).rows[0].g.messages.some(m => m.user_id === C), 'joueur bloqué : ses messages disparaissent');
ok((await as(B, 'select get_friends() f')).rows[0].f.list.every(f => f.id !== C), 'joueur bloqué : retiré des amis');
ok(await fails(as(C, `select friend_request($1)`, [codeB])) !== null, 'joueur bloqué : ne peut plus envoyer de demande');
ok((await as(B, 'select my_blocks() b')).rows[0].b.length === 1, 'liste des joueurs bloqués');
await as(B, `select block_user($1, false)`, [C]);
ok(await fails(as(B, 'select admin_reports()')) !== null, 'outils de modération réservés à l’administrateur');
await as(B, `select report('pseudo', $1, 'insulte')`, [C]);
await admin(`update profiles set is_admin = true where id = $1`, [A]);
const reps = (await as(A, 'select admin_reports() r')).rows[0].r;
ok(reps.length >= 2 && reps[0].n >= 3, `l’administrateur voit les signalements regroupés (${reps.length})`);
await as(A, `select admin_act('pseudo', $1, 'muet')`, [C]);
await admin(`update guild_messages set at = at - interval '5 seconds'`);
ok(/écrire avant/.test(await fails(as(C, `select guild_post('coucou')`)) || ''), 'joueur rendu muet 7 jours');
ok((await as(A, 'select admin_reports() r')).rows[0].r.every(r => r.ref !== C), 'signalement traité, retiré de la liste');
ok(await fails(as(C, `update profiles set muted_until = null where id = auth.uid()`)) !== null, 'impossible de lever soi-même la sanction');
await admin(`update profiles set is_admin = false, muted_until = null where id in ($1,$2)`, [A, C]);

console.log('Suppression de compte (RGPD)');
const D = (await admin(`insert into auth.users(email) values ('d@test.fr') returning id`)).rows[0].id;
await as(D, 'select get_state()');
await admin(`insert into cards(owner, species_id, q, lvl) values ($1,'pica-pica',50,1)`, [D]);
await admin(`update profiles set premium_until = now() + interval '20 days' where id = $1`, [D]);
ok(await fails(as(D, 'select delete_my_account()')) !== null, 'abonnement actif : résiliation demandée avant suppression');
await admin(`update profiles set premium_until = null where id = $1`, [D]);
await as(D, 'select delete_my_account()');
ok((await admin(`select (select count(*) from auth.users where id = $1) + (select count(*) from profiles where id = $1) + (select count(*) from cards where owner = $1) n`, [D])).rows[0].n == 0, 'compte, profil et cartes effacés');

console.log(`\n${pass} réussis, ${fail} échoués`);
await db.end();
process.exit(fail ? 1 : 0);
